### ISSUE TITLE
代码跑不起来

### ISSUE THREAD

**Issue by DaTongDXM** [mx-space/mx-admin#109]
我install之后，执行了npm run dev报错
`
'TAILWIND_MODE' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
`
这个命令我在网上搜不到，麻烦指点。

**Comment by Innei** [comment]
windows 用户？

**Comment by Innei** [comment]
windows 可能在定义环境变量上与 类 Unix 不同。

**Comment by DaTongDXM** [comment]
> windows 可能在定义环境变量上与 类 Unix 不同。

是windows用户，这个我该怎么处理呢？

**Comment by Innei** [comment]
> > windows 可能在定义环境变量上与 类 Unix 不同。
> 
> 
> 
> 是windows用户，这个我该怎么处理呢？

没有用过windows开发，可以去查一下windows定义env的方式，或者用 cross-env
