### ISSUE TITLE
设置主人名为空格会导致无法登录

### ISSUE THREAD

**Issue by suemor233** [mx-space/mx-admin#278]
在设定->用户->界面里面
当设置 "主人名 (username)" 为一个空格并保存，会出现无法登录的情况

<img width="900" alt="image" src="https://user-images.githubusercontent.com/89030875/154608710-f61e5967-ff2d-43ea-aee3-95bcb279c4bd.png">
<img width="900" alt="image" src="https://user-images.githubusercontent.com/89030875/154609670-160aa493-29fa-4eb7-a47b-64c6ed917845.png">
<img width="900" alt="image" src="https://user-images.githubusercontent.com/89030875/154608824-6e99e00a-949b-42f7-bc42-16c2b58fff20.png">

**Comment by Innei** [comment]
fix
