### ISSUE TITLE
请教大佬 这个和mx-server的关系是什么

### ISSUE THREAD

**Issue by oozry12** [mx-space/mx-admin#339]
用docker搭建了mx-server是否还需要这个admin

**Comment by Innei** [comment]
不需要

**Comment by oozry12** [comment]
ok.再请教一下，编辑器是很素吗？没有其他可以选的？切换了`monaco`和`codemirror`好像没区别啊
![image](https://user-images.githubusercontent.com/1807379/159258077-767f71fb-56bd-468f-854d-45320e1bd808.png)
