### ISSUE TITLE
错别字，嘿嘿

### ISSUE THREAD

**Issue by Yuri-NagaSaki** [mx-space/mx-admin#362]
![E_DMG7F{ 3)}_U4$9($ SE](https://user-images.githubusercontent.com/77047823/161415194-472979ce-f31f-45ac-b63e-19c7ff8fe9e9.png)

**Comment by Innei** [comment]
哪里

**Comment by Yuri-NagaSaki** [comment]
生活记录 撰写 然后离开未保存的话，再返回还原
![image](https://user-images.githubusercontent.com/77047823/161722675-b729c1ce-7fd9-48e3-ac5e-3dfb11853410.png)

**Comment by Innei** [comment]
欢迎 PR
