### ISSUE TITLE
删除数据库后，重新初始化站点会出现异常

### ISSUE THREAD

**Issue by suemor233** [mx-space/mx-admin#368]
删除数据库后，初始化站点(点击第3步的LINK START)，无法跳转到登录界面。似乎是因为cookie中依然存在被删除用户的token，导致请求后端发生500错误，我可以提一个PR来删除这个token

![three](https://user-images.githubusercontent.com/89030875/162447768-58163eac-6027-494a-aff2-66516d39e320.jpg)
![two](https://user-images.githubusercontent.com/89030875/162447889-16c03a3a-6d7c-4197-b8f4-acd2b34da7a5.jpg)

**Comment by Innei** [comment]
没有背景吗，没有背景也是 bug，可以随带看看

**Comment by suemor233** [comment]
确实，gitee外链被屏蔽了

**Comment by Innei** [comment]
#369
