### ISSUE TITLE
内存泄漏严重！

### ISSUE THREAD

**Issue by Innei** [mx-space/mx-admin#555]
内存泄漏严重！路由切换没有释放上一个路由的内存！！！！！！！原因未知

**Comment by Dreamer-Paul** [comment]
xswl

**Comment by wibus-wee** [comment]
早日换 react 😂

**Comment by miaoermua** [comment]
Innei 放心冲😂

**Comment by wuhang2003** [comment]
https://github.com/facebookincubator/memlab
试一下这个？
前几天开源的一个查找 JavaScript 内存泄漏和分析堆快照的框架

**Comment by ttimochan** [comment]
> https://github.com/facebookincubator/memlab 试一下这个？ 前几天开源的一个查找 JavaScript 内存泄漏和分析堆快照的框架

带我！

**Comment by wuhang2003** [comment]
> > https://github.com/facebookincubator/memlab 试一下这个？ 前几天开源的一个查找 JavaScript 内存泄漏和分析堆快照的框架
> 
> 带我！

提莫带带我！
