### ISSUE TITLE
后台 setup-api 设置 API 和网关地址后点确定出现异常

### ISSUE THREAD

**Issue by wuhang2003** [mx-space/mx-admin#582]
经群里反馈和本人测试，在用 Docker 部署完 Core 完成初始化过程后管理后台上方仍出现 custom-api 的黑条，点进去设置 API 及网关地址后出现异常，在重新进入后台后黑条依旧存在，无论是否在 setup-api 那边勾选持久化。
![图片](https://user-images.githubusercontent.com/108316419/191551653-e58b72d3-a9f5-4111-94dc-d6ac968bb758.png)
![图片](https://user-images.githubusercontent.com/108316419/191551843-abf94b96-7825-4390-9c88-039413e35fb1.png)

**Comment by ttimochan** [comment]
顶部黑条存在是正常的

api 接口你确定你带上 referer 请求了么

**Comment by ttimochan** [comment]
api 接口你确定你带上 referer 请求了么

**Comment by ttimochan** [comment]
经过我测试，直接访问了后台，不需要设置 API，不知道怎么复现

**Comment by Innei** [comment]
admin 没有提供 docker 镜像。

**Comment by ttimochan** [comment]
> 经群里反馈和本人测试，在用 Docker 部署完 Core 完成初始化过程后管理后台上方仍出现 custom-api 的黑条，点进去设置 API 及网关地址后出现异常，在重新进入后台后黑条依旧存在，无论是否在 setup-api 那边勾选持久化。 ![图片](https://user-images.githubusercontent.com/108316419/191551653-e58b72d3-a9f5-4111-94dc-d6ac968bb758.png) ![图片](https://user-images.githubusercontent.com/108316419/191551843-abf94b96-7825-4390-9c88-039413e35fb1.png)

请使用 /proxy/qaqdmin

**Comment by wuhang2003** [comment]
> > 经群里反馈和本人测试，在用 Docker 部署完 Core 完成初始化过程后管理后台上方仍出现 custom-api 的黑条，点进去设置 API 及网关地址后出现异常，在重新进入后台后黑条依旧存在，无论是否在 setup-api 那边勾选持久化。 ![图片](https://user-images.githubusercontent.com/108316419/191551653-e58b72d3-a9f5-4111-94dc-d6ac968bb758.png) ![图片](https://user-images.githubusercontent.com/108316419/191551843-abf94b96-7825-4390-9c88-039413e35fb1.png)
> 
> 请使用 /proxy/qaqdmin

虽然但是，发 issues 的时候用的就是 /proxy/qaqdmin（
最新版解决黑条啦？

**Comment by ttimochan** [comment]
@wuhang2003 emmmm，那我不清楚，我自己是单独部署后台的，用了 CI/CD 进行自动化

**Comment by wuhang2003** [comment]
> @wuhang2003 emmmm，那我不清楚，我自己是单独部署后台的，用了 CI/CD 进行自动化

🤔
