### ISSUE TITLE
升级后出错，后台时而打得开时而打不开

### ISSUE THREAD

**Issue by yuano0** [mx-space/mx-admin#651]
### 使用配置

环境：Ubuntu / 20.04 LTS amd64 (64bit) 

### 出现问题

后台升级管理中台（当前版本: 3.25.0，最新版本: 3.25.3），更新到最后报错

![Snipaste_2022-12-21_17-20-07](https://user-images.githubusercontent.com/106160716/208876990-bd1edbcb-e04d-447d-8b33-15015d785a01.png)

然后访问后台时而可以访问进，时而访问不进（进不去为大多数）

![2](https://user-images.githubusercontent.com/106160716/208877058-7f1d2288-a784-417e-8fe2-68280c4897db.png)

求助呜呜呜

**Comment by Innei** [comment]
Revert 了，一会发版
