### ISSUE TITLE
404: Not Found

### ISSUE THREAD

**Issue by miaoermua** [mx-space/mx-admin#686]
### Describe the bug

访问后端管理页 /qaqdmin#/dashboard 报 404: Not Found；改到 /proxy/qaqdmin#/dashboard 后正常

使用手动部署方式安装，无单独部署管理页

### Reproduction

{api}/qaqdmin#/dashboard

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 865.93 MB / 15.42 GB
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.78)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
怎么配置反代的。 网站的 `/qaqdmin` 需要反代到 core 服务的 `/qaqdmin`

**Comment by miaoermua** [comment]
> 怎么配置反代的。 网站的 `/qaqdmin` 需要反代到 core 服务的 `/qaqdmin`

按照 Docs 的后端反向代理

**Comment by Innei** [comment]
> > 怎么配置反代的。 网站的 `/qaqdmin` 需要反代到 core 服务的 `/qaqdmin`
> 
> 按照 Docs 的后端反向代理

发下反代配置我看下
