### ISSUE TITLE
[Feature request] Translation to English, possible/how hard ?

### ISSUE THREAD

**Issue by AkechiShiro** [mx-space/mx-admin#777]
### Clear and concise description of the problem

Hi,

Is it possible to translate this project or add internalization ? How hard would that be, I'm not very knowledgeable with the tech stack used (NodeJS/VueJS)

### Suggested solution

 but I'm not sure if one of these solution could be used : 
- https://locize.com/blog/i18next-vue/ 
- https://vue-i18n.intlify.dev/guide/

### Alternative

Use the website by translating them using an extension in the browser, the translation isn't perfect but it could allow usage as a workaround.

### Additional context

I could try and work on it, but with guidance and an accepted solution discussed with the maintainers of this repo.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
Hi, thanks for the suggestion. So far, I've thought the audience for this project will be Chinese users, so I haven't thought about i18n. Accessing i18n is a huge undertaking because the project is now taking shape.

I have plans to rewrite this project (if I have a lot of free time), along with the mx-space/core project, of course. After that, maybe I won't use Vue-related technology stacks anymore.

Anyway, thank you so much for letting me see the impact of this project

**Comment by AkechiShiro** [comment]
Feel free, to tag me when you are going to do the rewrites if I can provide any help, I don't think I'm as well versed in front end, but I'll be interested to help and learn as best as I can on simple issues.

What kind of tech stack will the rewrite use if that has been decided ? ReactJS ?

**Comment by Innei** [comment]
> Feel free, to tag me when you are going to do the rewrites if I can provide any help, I don't think I'm as well versed in front end, but I'll be interested to help and learn as best as I can on simple issues.
> 
> What kind of tech stack will the rewrite use if that has been decided ? ReactJS ?

Yes, React will be my first choice. However, there is a huge amount of work involved in migrating from one framework to another. I plan to rewrite the entire server-side first and then refactor the dashboard.

**Comment by Innei** [comment]
Currently, I am learning Prisma, and after several days of trying, I think Prisma is very user-friendly compared to Typegoose. It is more type-safe and easier to maintain.

**Comment by Innei** [comment]
@AkechiShiro Hi, I'm currently working on [this project](https://github.com/Innei/MetaMuse), completely rewriting the entire system using trpc + prisma. By the way, I'm also adding support for i18n.
