### ISSUE TITLE
api文档

### ISSUE THREAD

**Issue by eell-os** [mx-space/mx-admin#878]
作者大大，首先感谢您开源mx admin，我是上个月用这个开源项目的，非常棒的管理面板!我希望作者能出一些api文档用于调用，这样能实现更多的功能和个性化

**Comment by Innei** [comment]
个人原因，目前没有精力去维护接口文档，目前接口有一百多个，我不可能把非 C 端的接口用法都写出来。有能力的可以直接看代码，代码现在的结构是很清晰的。

对于 C 端接口，我这边提供了 SDK 可以直接调用。
