### ISSUE TITLE
文章縮略圖因不明原因無法顯示

### ISSUE THREAD

**Issue by seriaati** [mx-space/mx-admin#888]
### Describe the bug

在「文章設定」中填寫了文章縮略圖的連結，底下的 cover 欄位裡也有正常出現
![image](https://github.com/mx-space/mx-admin/assets/61446626/0f86ec64-80f2-4487-8420-195ce470dbce)
將鼠標放置在連結上時，圖片也有正常出現
![image](https://github.com/mx-space/mx-admin/assets/61446626/e4695758-7903-4997-b6d6-13f24066af5e)
點擊自動修正時，會顯示錯誤訊息
![image](https://github.com/mx-space/mx-admin/assets/61446626/87b18489-24d6-48d4-84ed-1305a232fde4)
在文章中，沒有出現縮略圖
![image](https://github.com/mx-space/mx-admin/assets/61446626/04bc0810-290b-474a-bc77-6ae68540008a)

我猜想可能是因為這個圖片連結並不是以檔名結尾的？

文章連結：https://seria.vercel.app/notes/3
圖片連結：https://photos.seriaati.xyz/api/v1/t/a68835255d0640dfbd34e4b12a22a3f15b934916/1okg2wda/fit_1280

### Reproduction

Described above

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 AMD EPYC-Rome Processor
    Memory: 1.00 GB / 3.82 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.19.0 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm

API: https://mx-space.seriaati.xyz/api/v2
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
我这里看是正常的哦

**Comment by seriaati** [comment]
由於 issue 太久沒有人回應，我之前就用更改圖源的方式修好了，此問題仍然存在。
![image](https://github.com/mx-space/mx-admin/assets/61446626/bdb34efb-815e-4e99-8e10-a0008a303520)
