### ISSUE TITLE
admin_web无法删除文件

### ISSUE THREAD

**Issue by yuanxi953** [mx-space/mx-admin#905]
### 复现步骤
我采用的是Docker部署
- 1、转到admin前端（https://server.example.com/proxy/qaqdmin）
- 2、点击`文件`菜单
- 3、随便单击子选项`图标`、`头像`、`文件`
- 4、尝试点击`删除`任意文件，提示`删除成功`
- 5、随意来回切换子选项`图标`、`头像`、`文件`或者刷新，被删除的文件又诈尸了，且这文件还能正常以链接形式访问

### Reproduction

https://alist.yuanxi953.cn:4433/BUG%E5%8F%8D%E9%A6%88%E7%9B%B8%E5%85%B3/mx-space_mx-admin_2024-05-20%2017-32-16.mkv

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum
    Memory: 412.82 MB / 1.69 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.11.1 - /usr/local/NodeJS/node-v20.11.1-linux-x64/bin/node
    npm: 10.2.4 - /usr/local/NodeJS/node-v20.11.1-linux-x64/bin/npm


{
    "name": "@mx-space/core",
    "author": "Innei <https://innei.ren>",
    "version": "5.7.6",
    "homepage": "https://github.com/mx-space/core/tree/master/apps/core#readme",
    "issues": "https://github.com/mx-space/core/issues"
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
你这个问题应该是文件删除失败了，看看日志的错误信息，盲猜是没权限

**Comment by yuanxi953** [comment]
> 你这个问题应该是文件删除失败了，看看日志的错误信息，盲猜是没权限

以下是错误日志，我并不太清楚是何原因导致的，可能因为我是Debian？

ERROR   [System]  删除文件失败 EXDEV: cross-device link not permitted, rename '/root/.mx-space/static/file/xbs9m63edm48ki5039.png' -> '/tmp/mx-space/trash/xbs9m63edm48ki5039.png'

![image](https://github.com/mx-space/mx-admin/assets/99540778/197b70cd-89bc-41be-a7b6-30adacf65910)

**Comment by Innei** [comment]
错误信息问问 gpt 试试
