### ISSUE TITLE
博客后台的分类栏能否新增自定义排序的功能

### ISSUE THREAD

**Issue by lebenito030** [mx-space/mx-admin#934]
### Clear and concise description of the problem

目前的文稿类别貌似是和后台的顺序保持一致来进行显示的，但是要更换类别的位置的话目前后台并没有一个方便的能自定义顺序的功能

### Suggested solution

1. 新增一个可以拖动更改顺序的功能

### Additional context

其实我是想试着自己实现一下来提PR的，不过在本地部署的 mx-admin 使用已经部署在服务器上的 api 服务时貌似会有跨域的问题，这个有啥解决方法吗（抱歉，还是我太菜了_(:з」∠)_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by suemor233** [comment]
在 core docker-compose.yml ALLOWED_ORIGINS 里加上 `localhost:*,127.0.0.1:*`，本地就不会有跨域问题了

**Comment by lebenito030** [comment]
> 在 core docker-compose.yml ALLOWED_ORIGINS 里加上 `localhost:*,127.0.0.1:*`，本地就不会有跨域问题了

感谢佬，我解决了
