### ISSUE TITLE
如何获取一个不限制时间的token

### ISSUE THREAD

**Issue by eell-os** [mx-space/mx-admin#946]
我尝试获取mix-space里的数据，但似乎没有一个不受时间限制的token

我尝试使用ey开头的token进行请求api，但过段时间他会提示身份过期

我在 设定里的安全 生成一个 API Token，但发现是txo开头的，我尝试使用这个token替换令牌，但提示无效

关于bug:
我在设定里的安全 生成一个 API Token，开头是txo开头的，生成之后并没有在列表中显示

![image](https://github.com/user-attachments/assets/ffa8db13-aaf6-4b3d-96d2-0cde9e9a12b1)

**Comment by Innei** [comment]
>  我在设定里的安全 生成一个 API Token，开头是txo开头的，生成之后并没有在列表中显示

确实是 bug，已修复。

txo 开头的 token 不需要 bearer 前缀。参考 https://github.com/mx-space/mx-tg-bot
